name: papayas_analyzer
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  flutter_svg: ^2.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  animated_snack_bar: ^0.4.0
  carousel_slider: ^5.0.0
  image: ^4.5.4
  equatable: ^2.0.7
  photo_view: ^0.15.0
  tflite_flutter: ^0.11.0
  flutter_launcher_icons: ^0.14.3
  go_router: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/tensorflow/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/app-icon.png"
  adaptive_icon_background: "assets/images/app-icon.png"
  adaptive_icon_foreground: "assets/images/app-icon.png"
